#!/bin/bash
#
# search
#
# Provides an easier way to search for text, files, and directories
################################################################################

action="${1}"
shift
term=${@}

function search_text()
{
    echo "Searching for text ${1}"
}

function search_file()
{
    echo "Searching for file ${1}"
}

function search_dir()
{
    echo "Searching for dir ${1}"
}


case "${action}" in
    text)
        search_text ${term}
        ;;
    file)
        search_file ${term}
        ;;
    dir)
        search_dir ${term}
        ;;
esac

