#!/bin/bash

bl_dirs=""
wl_exts="c h cpp hpp py asm S s"

# Candidate files file
cand_file="GFILES"

function build_prune_str()
{
    echo -n ""
}

function build_include_str()
{
    echo -n ""
}

function generate_tags()
{
    if [[ -z "${wl_exts}" ]]; then
        echo "No extensions specified, define \$wl_exts to continue"
        exit
    fi

    prune_str=`build_prune_str "${bl_dirs}" "${bl_exts}"`
    include_str=`build_include_str "${wl_dirs}" "${wl_exts}"`

    echo "Generating tag database"
    options="--color=never --files"
    rg ${prune_str} ${include_str} ${options} > ${1}
}

case "${1}" in
    clean)
        echo "Cleaning tag database files"
        rm -f GTAGS GRTAGS GPATH ${cand_file}
        ;;

    *)
        if [[ "${1}" ]]; then
            cand_file="${1}"
        fi
        generate_tags ${cand_file}
        ;;
esac

